spring:
  security:
    oauth2:
      client:
        provider:
          auth0:
            issuer-uri: https://<dev-ga7njuw5als2pp77.us.auth0.com>/
        registration:
          auth0:
            client-id: <YEwYBH3Y6AyTiZ0Cl2SUie3KUWQqYeNmU>
            client-secret: <EwYBH3Y6AyTiZ0Cl2SUie3KUWQqYeNmU>
            scope: openid,profile,email
